#!/bin/bash

# Installing npm packages
npm install glob
npm install dotenv
npm install request
npm install split-file
npm install fs-extra

# Creating a directory to contain media
mkdir ./media

# Creating an incomplete .env file
touch ./.env
echo 'CONSUMER_KEY=' >> ./.env
echo 'CONSUMER_KEY_SECRET=' >> ./.env
echo 'ACCESS_TOKEN=' >> ./.env
echo 'ACCESS_TOKEN_SECRET=' >> ./.env

printf '\ndone.\n\n'
